alias 'gst'="git status"
alias 'gco'='git checkout'
alias 'gb'="git branch"
alias 'gpull'="git pull origin"
alias 'gpush'="git push origin"
alias 'gadd'="git add" 
alias 'gl'="git log"
alias 'gfetch'="git fetch -p"
alias 'gd'="git diff"